# Generated by Django 3.2.8 on 2022-04-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_libro_descipcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
